name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: zip -r Openly.zip Openly -x "*.DS_Store"
      
      - name: Create release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generateReleaseNotes: true
          artifacts: Openly.zip
          token: ${{ secrets.GITHUB_TOKEN }}

